### ISSUE TITLE
invalid definition, a declaration named 'foo' has already been declared

### ISSUE THREAD

**Issue by kbuzzard** [mpedramfar/Lean-game-maker#10]
I updated the natural number game and now I get a weird error if I skip directly to level 10 of advanced proposition world and solve it with
```
by_cases P,
{ by_cases Q,
  cc,
  cc
},
{ by_cases Q,
  cc,
  cc
},
```

I get
```
53:6: error:
invalid definition, a declaration named 'contrapositive2' has already been declared
```
in the error box. But the only time `contrapositive2` is mentioned in my code is in that one file.

Any idea what's going on?

**Comment by mpedramfar** [comment]
I can't replicate the error. Do you get this error every time you do this? Will you still get the error if you clean the browser cache and reload the page?

**Comment by kbuzzard** [comment]
I can't replicate it either now. I suspect clearing the cache solved it. Or maybe it's the fact that I'm now playing with the real number game as well as the natural number game? Could this be an issue? Note https://github.com/ImperialCollegeLondon/natural_number_game/issues/73#issuecomment-629818116 . Should different games interfere with each other?

**Comment by mpedramfar** [comment]
This issue is not the same as the invalid definition. The game is saved in localStorage which will remain intact after cleaning the cache. I thought localStorage is url specific while it's actually domain specific. So in the previous commits, if you run two games from the same domain, the saved game data would be messed up.
In the latest commit, I've made some changes so that you can run two different games on the same domain.

**Comment by mpedramfar** [comment]
I think I know what cause the main issue. Now different games don't touch each other's save data, but they save `library.zip` in the same place. So they might be able interfere with each other if you open two games with different libraries at the same time.
To fix that, I would need to change the `lean-client-js-browser` repository. Adding an entire repository to the project, just to change a few lines, doesn't seem to be optimal.

One way to fix the issue, for now, is to develop all the games that are meant to be run from the same domain in the same Lean project. Then you can have different `game_config.toml` files for different games.

**Comment by mpedramfar** [comment]
I asked Bryan about this and it turns out that there is no need to change any other repo. I implemented the required changes in the last commit. Note that if you have two games running from the same domain and one of them is not using the new commit, then loading that page interferes with the new one. But if all pages are built with the new version, they won't interfere with each other.
